### ISSUE TITLE
Kotlin Error

### ISSUE THREAD

**Issue by 0xC1A551C** [RHazDev/CommandsDispatcher#2]
```
[21:36:11 WARN]: Error enabling plugin Dispatcher
java.lang.NoClassDefFoundError: kotlin/TypeCastException
at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_191]
at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_191]
at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_191]
at java.lang.Class.getDeclaredConstructor(Class.java:2178) ~[?:1.8.0_191]
at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:361) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:52bc4fe:273]
at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:268) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:52bc4fe:273]
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:270) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:52bc4fe:273]
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:52bc4fe:273]
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:52bc4fe:273]
Caused by: java.lang.ClassNotFoundException: kotlin.TypeCastException
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:52bc4fe:273]
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:52bc4fe:273]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191]
... 9 more
```

**Comment by hazae41** [comment]
https://jitpack.io/com/github/hazae41/mc-dispatcher/master-SNAPSHOT/mc-dispatcher-master-SNAPSHOT-bundle.jar
try this one
